config/routes.rb
Rails.application.routes.draw do
  get 'converter/index'
  get 'converter/convert'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/recipe_info", to: "recipe_info#index"
  resources :recipes, only: [:show, :create, :destroy, :index, :edit, :update] do
    resources :recipe_timers, only: [:create]
  end

  resources :recipe_timers, only: [:edit, :update, :destroy]
  resources :timers, only: [:index, :destroy, :create, :edit, :update]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_timers, dependent: :destroy
  validates :name, presence: true
end

app/models/recipe_info.rb
class RecipeInfo < ApplicationRecord
end

app/models/recipe_timer.rb
class RecipeTimer < ApplicationRecord
  belongs_to :recipe

  validates :ingredient, :time, presence: true
  validates :time, numericality: { greater_than: 0 }
  # validates :recipe, presence: true

  def time_in_minutes
    if time.to_f >= 60
      hours = (time / 60).floor
      remaining_time = time % 60
      "#{hours}:#{remaining_time.to_i.digits.size == 1 ? "0" : ""}#{remaining_time.to_i}:#{(60*(time - time.to_i)).to_i.digits.size == 1 ? "0" : ""}#{(60*(time - time.to_i)).to_i}"
    else
      "#{time.to_i}:#{(60*(time - time.to_i)).to_i}"
    end
  end
end

app/models/timer.rb
class Timer < ApplicationRecord
  include PgSearch::Model
  # belongs_to :user

  validates :ingredient, :time, presence: true
  validates :time, numericality: { greater_than: 0 }

  pg_search_scope :search_by_ingredient_and_time,
  against: [ :ingredient, :time ],
  using: {
    tsearch: { prefix: true }
  }

  def time_in_minutes
    if time >= 60
      hours = (time/60).floor
      p hours
      remaining_time = time % 60
      p remaining_time
      "#{hours}:#{remaining_time.to_i.digits.size == 1 ? "0" : ""}#{remaining_time.to_i}:#{(60*(time - time.to_i)).to_i.digits.size == 1 ? "0" : ""}#{(60*(time - time.to_i)).to_i}"
    else
      "#{time.to_i}:#{(60*(time - time.to_i)).to_i}"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :timers
  has_many :recipes
  has_many :recipe_timers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/recipe_info_controller.rb
class RecipeInfoController < ApplicationController
end

app/controllers/recipe_timers_controller.rb
class RecipeTimersController < ApplicationController
  # def show
  #   @recipe_timers = RecipeTimer.all
  #   @recipe_timer = RecipeTimer.find(params[:id])
  #   @new_recipe_timer = RecipeTimer.new
  # end

  def edit
    # raise
    @recipe_timer = RecipeTimer.find(params[:id])
  end

  def create
    @recipe_timer = RecipeTimer.new(recipe_timer_params)
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_timer.recipe = @recipe
    if @recipe_timer.save!
      redirect_to recipe_path(@recipe)
    else
      render "recipes#show", status: :unprocessable_entity
    end

  end

  def destroy
    @recipe_timer = RecipeTimer.find(params[:id])
    @recipe_timer.destroy
    redirect_to recipe_timer_path, status: :see_other
  end

  def update
    @recipe_timer = RecipeTimer.find(params[:id])
    if @recipe_timer.update(recipe_timer_params)
      redirect_to recipe_path(@recipe_timer.recipe)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def recipe_timer_params
    params.require(:recipe_timer).permit(:ingredient, :time)
  end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipes = Recipe.where(user: current_user)
    @recipe = Recipe.find(params[:id])
    @new_recipe = Recipe.new
    @new_timer = RecipeTimer.new
  end

  # def new
  #   @recipe = Recipe.new
  # end

  def index
    @recipes = Recipe.where(user: current_user)
    @new_recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, status: :see_other
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :instructions)
  end
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  def index
    # @timers = Timer.all
    @timer = Timer.new

    if params[:query].present?
      if params[:query].match(/\d/)
        sql_query = "time = :query"
        @timers = Timer.where(sql_query, query: params[:query].to_f)
      else
      # @timers = Timer.where(sql_query, query: "%#{params[:query]}%")
      # sql_query = "ingredient ILIKE ?"
      sql_query = "ingredient ILIKE :query"
      @timers = Timer.where(sql_query, query: "%#{params[:query]}%")
      end
    else
      @timers = Timer.where(user_id: current_user).or(Timer.where(user_id: nil))
    end
  end

  def edit
    @timer = Timer.find(params[:id])
  end

  # def new
  #   @timer = Timer.new
  # end

  def create
    @timer = Timer.new(timer_params)
    @timer.user_id = current_user.id
    @timer.save
    redirect_to timers_path(@timer)
  end

  def destroy
    @timer = Timer.find(params[:id])
    @timer.destroy
    redirect_to timer_path status: :see_other
  end

  def update
    @timer = Timer.find(params[:id])
    if @timer.update(timer_params)
      redirect_to timers_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end
end

private

def timer_params
  params.require(:timer).permit(:ingredient, :time)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <title>TimeToCookRailsApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="bk-img">
  <div class="text-white">
    <div class="container cta">
      <div class="site-information">
        <h1 class="home-page-text p-4" >No longer will the smoke alarm be used to cook!</h1>


  <div class="btn btn-homepage" id="home-btn"> <%= link_to "Time to cook!", timers_path %> </div>
      </div>
    </div>


<div class="cards">
  <div class="card-category" style="" id="opacity-d-timers">
    <h2 class="home-cards-text"> Quick access to timers</h2>
    <p>We have provided pre-set timers for commonly cooked dishes, allowing users to easily select and start timers for popular recipes without manually inputting time settings.</p>


  </div>

  <div class="card-category" style="" id="opacity-my-timers">
    <h2 class="home-cards-text"> The ability to make your own timers</h2>
    <p>My timers allow users to customize and save their own timers for specific dishes or cooking techniques, providing a personalized collection of timers that can be easily accessed and reused.</p>
  </div>

  <div class="card-category" style="" id="opacity-recipes">
    <h2 class="home-cards-text"> Browse suggested recipes</h2>
    <p>The recipes page offers a vast selection of culinary creations, guiding users through step-by-step instructions and providing corresponding timers for each recipe. This feature ensures that users can follow recipes seamlessly and achieve optimal results by syncing timers with specific cooking steps.</p>
  </div>
</div>

  </div>
</div>




<%#
<div class="timer-group">
  <div class="timer hour">
    <div class="hand"><span></span></div>
    <div class="hand"><span></span></div>
  </div>
  <div class="timer minute">
    <div class="hand"><span></span></div>
    <div class="hand"><span></span></div>
  </div>
  <div class="timer second">
    <div class="hand"><span></span></div>
    <div class="hand"><span></span></div>
  </div>
  <div class="face">
    <h2>A timer</h2>
    <p id="lazy">00:00:00</p>
  </div>
</div> %>

app/views/recipe_timers/edit.html.erb
<p><%= link_to 'Back to Recipe', recipe_path(@recipe_timer.recipe), class: 'p-2 m-3 btn btn-edit-recipes'%></p>
<div class="p-5">
<h1>Edit the timer for <%= @recipe_timer.ingredient %></h1>
</div>
<div style="display: flex; justify-content: center;">
<%= simple_form_for @recipe_timer do |f| %>
<%= f.input :ingredient, input_html: { style: 'width: 400px' } %>
<%= f.input :time, label: 'Time(minutes)' input_html: { style: 'width: 400px' } %>
  <%= f.submit %>
    </div>
  <% end %>
 <div class="p-5">
<h1>Tailor Time to Perfection: Craft Your Culinary Countdowns!</h1>
</div>

app/views/recipes/edit.html.erb
<p><%= link_to 'Back to Recipes', recipes_path(@recipe), class: 'p-2 mt-3 btn btn-edit-recipes'%></p>
<div class="p-5">
  <h1>Edit the timer for <%= @recipe.name  %></h1>
</div>
<div class="d-flex justify-content-center" >
  <%= simple_form_for @recipe do |f| %>
    <%= f.input :name, input_html: { style: 'width: 400px' } %>
    <%= f.input :instructions, input_html: { style: 'width: 400px' } %>
    <%= f.submit %>
  <% end %>
</div>
</div>
<div class="p-5">
  <h1>Master the Minutes: Fine-Tune Your Recipes!</h1>
</div>
<%= link_to ('<i class="bin-recipes fa-solid fa-trash p-2"></i>').html_safe, recipe_path(@recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/recipes/index.html.erb
<div class="d-flex">

<div class="recipe-bar-index">
<div class="d-flex justify-content-around align-items-center">
  <h1 style="margin-right: -40px; ">Recipes</h1>
  <button type="button" class="add-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
    <i class="fa-solid fa-circle-plus fa-lg" style=></i>
  </button>
</div>
  <ul><% @recipes.each do |recipe|%>
        <li class="list-unstyled">
            <%= link_to recipe_path(recipe), class: 'recipe-link' do %>
                    <div class="recipe-name">
                      <%= recipe.name %>
                    </div>
                  <% end %>
            <%# <%= link_to recipe.name, recipe_path(recipe), class: 'recipe-link' %>

            <%# <%= link_to ('<i class="fa-solid fa-trash"></i>').html_safe, recipe_path(recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
             <%# <%= link_to ('<i class="fa-sharp fa-solid fa-pen"></i>').html_safe, edit_recipe_path(recipe) %>
        </li>
      <% end %>
  </ul>

  <%# <%= simple_form_for @new_recipe, html: { class: "narrow-form" } do |f|  %>
  <%# <%= f.input :name %>
  <%# <%= f.submit %>
  <%# <% end %>
</div>
  <h1 class="recipe-index-text">Click on a recipe to access your timers!</h1>
</div>


<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add a new recipe</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @new_recipe do |f|  %>
          <%= f.input :name %>
          <div class="d-flex justify-content-center">
            <%= f.submit "Add Recipe", class: "btn btn-primary"  %>
          </div>

        <% end %>
      </div>
      <%# <div class="modal-footer"> %>
      <%# </div> %>
    </div>
  </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

app/views/recipes/show.html.erb
<div class="d-flex">

  <div class="d-flex recipe-bar" >
    <div class="recipes w-100">
      <h1 class="m-3 display-5">Recipes</h1>
      <ul><% @recipes.each do |recipe|%>
            <li class="list-unstyled">
                <% if recipe.user_id == @recipe.id %>
                  <%= link_to recipe_path(recipe), class: 'recipe-link' do %>
                    <div class="recipe-name">
                      <%= recipe.name %>
                    </div>
                  <% end %>
                <% else %>
                   <%= link_to recipe_path(recipe), class: 'recipe-link' do %>
                    <div class="recipe-name">
                      <%= recipe.name %>
                    </div>
                  <% end %>
                <% end %>


                <%# <% unless recipe.id == @recipe.id%>
                <%# <%= link_to ('<i class="fa-solid fa-trash"></i>').html_safe, recipe_path(recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                 <%# <% end %>
                <%# <%= link_to ('<i class="fa-sharp fa-solid fa-pen"></i>').html_safe, edit_recipe_path(recipe) %>
            </li>
          <% end %>
      </ul>

      <%# <%= simple_form_for @new_recipe do |f|  %>
      <%# <%= f.input :name, label: "Name:" %>
      <%# <%= f.submit "Add Recipe" %>
      <%# <% end %>
    </div>
  </div>


  <div class="flex-grow-1 px-4">
    <div class="d-flex flex-column">
      <div class="d-flex justify-content-center align-items-center">
        <h1 id="recipe-name" class="m-3 display-5" ><%= @recipe.name %></h1>
        <%= link_to edit_recipe_path do %>
          <i class="fa-sharp fa-solid fa-pen p-1"></i>
        <% end %>

      </div>

      <% if @recipe.recipe_timers.any? %>
        <div class="container">
          <div class="d-flex align-items-center justify-content-center" >
          </div>
          <div class="timer-grid h5">
            <% @recipe.recipe_timers.each do |timer| %>
            <div class="timer-card" data-controller="timers" data-timers-initial-time-value=<%=timer.time_in_minutes%>>
              <%= timer.ingredient %>
              <div class="timer-circle display-5" data-timers-target="button" data-action="click->timers#start">
                  <%= timer.time_in_minutes %>
                  <%# <audio data-timers-target="audio" src="app/assets/sounds/explosion.mp3"></audio> %>
                  <%= audio_tag "alarm.mp3", data: {timers_target: 'audio'} %>
              </div>
              <div class="icons-timer">
                <button class="reset-button fa-solid fa-arrows-rotate p-1"  data-action="click->timers#reset"></button>
                <% if timer.recipe.user_id == current_user.id %>
                  <%= link_to ('<i class="fa-solid fa-trash p-2"></i>').html_safe, recipe_timer_path(timer), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  <%= link_to ('<i class="fa-sharp fa-solid fa-pen p-1"></i>').html_safe, edit_recipe_timer_path(timer)%>
                <% end %>
              </div>





            </div>
            <% end %>

          </div>
        </div>
      <% end %>


    <div class="create">
      <%= simple_form_for [ @recipe, @new_timer ] do |f|  %>
          <%= f.input :ingredient %>
          <%= f.input :time %>
          <div class="d-flex justify-content-center">
            <%= f.submit :"Add Timer", class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-light">
  <div class="nav-bar-color container-fluid">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Time to cook (2).png" %>

    <% end %>

    <div class="d-flex w-4 justify-content-between" style="width: 900px; font-size: 25px">
     <div class="nav-bar-links"> <%= link_to "Quick Timers", timers_path %> <i class="fa-regular fa-clock"></i></div>
     <div class="nav-bar-links"> <%= link_to "My Timers", recipes_path %> <i class="fa-solid fa-clock"></i> </div>
     <div class="nav-bar-links"> <%= link_to "Explore Recipes", recipe_info_path %> <i class="fa-solid fa-book-open"></i> </div>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <%# <%= image_tag "https://freeiconshop.com/wp-content/uploads/edd/settings-solid.png", class: "settings", id: "darkModeIcon" %>

      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">


          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://media.istockphoto.com/id/1252403518/vector/vector-illustration-of-the-chef-avatar-icon.jpg?s=612x612&w=0&k=20&c=asppr7OWiM54V-YlGBuROvxrWSQ52GTjYIV9MoL2KRs=", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Action", "#", class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/timers/edit.html.erb
 <div class="p-5">
<h1>Edit the timer for <%= @timer.ingredient %></h1>
</div>
<div style="display: flex; justify-content: center;">
<%= simple_form_for @timer do |f| %>
<%= f.input :ingredient, input_html: { style: 'width: 400px' } %>
<%= f.input :time, input_html: { style: 'width: 400px' } %>
  <%= f.submit %>
  </div>
  <% end %>
  <div class="p-5">
<h1>Master the Minutes: Fine-Tune Your Cooking Clocks!</h1>
  </div>

app/views/timers/index.html.erb
<h1 class="m-3 display-5" >Timers</h1>
<h4 class="click-on-info text-center" >Click on a timer to start or pause the countdown!</h4>
<div class="search">
  <%= form_with url: timers_path, method: :get, class: "" do %>
    <div class="input-group">
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a timer" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="timer-grid">

    <% @timers.each do |timer| %>
      <div class="timer-card" data-controller="timers" data-timers-initial-time-value=<%=timer.time_in_minutes%>>
        <%= timer.ingredient %>
        <div class="timer-circle display-5" data-timers-target="button" data-action="click->timers#start">
          <%= timer.time_in_minutes %>
          <%= audio_tag "alarm.mp3", data: {timers_target: 'audio'} %>
        </div>
        <div>
          <button class="reset-button fa-solid fa-arrows-rotate p-1"  data-action="click->timers#reset"></button>
          <% if timer.user_id == current_user.id %>
            <%= link_to ('<i class="fa-solid fa-trash p-2"></i>').html_safe, timer_path(timer), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            <%= link_to ('<i class="fa-sharp fa-solid fa-pen p-1"></i>').html_safe, edit_timer_path(timer)%>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>



  <%# <div id="defaultParamsExample">
      <div class="values"></div> %>
  </div>
<div class="container">
  <div class="p-3 create" style="display: flex; justify-content: center;">
  <%= simple_form_for @timer do |f| %>
    <%= f.input :ingredient, input_html: { style: 'width: 350px' } %>
    <%= f.input :time, label: 'Time(minutes)', input_html: { style: 'width: 350px' } %>
    <%= f.submit "Create Timer", class: "btn btn-primary" %>


  <% end %>
  </div>
</div>